ps_store_monitor/ps_monitor/urls.py
from django.contrib import admin
from django.urls import path
from .views import GameItemView, GameItemCreate, GameItemListView, GameItemNewlyAddedListView, watch_unwatch, signup

urlpatterns = [
    path('', GameItemListView.as_view(), name='home'),
    path('newly', GameItemNewlyAddedListView.as_view(), name='newly_added'),
    path('new', GameItemCreate.as_view(), name='item_new'),
    path("item/<str:slug>/", GameItemView.as_view(), name="item_detail"),
    path("watch_unwatch/<int:pk>/", watch_unwatch, name="watch_unwatch"),
    path(r'signup/', signup, name='signup'),
]

ps_store_monitor/ps_store_monitor/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from ps_store_monitor import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include(('ps_monitor.urls', 'ps_monitor'), namespace='ps_monitor'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ps_store_monitor/ps_monitor/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class UrlItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    url = models.URLField(max_length=200)
    name = models.CharField("Name", max_length=100)
    need_to_monitor = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'[{self.user}] {self.name} - {self.url}'


class GameItem(models.Model):
    url = models.URLField(max_length=200, blank=True, null=True)
    url_item = models.ForeignKey(UrlItem, on_delete=models.CASCADE, null=True)
    name = models.CharField("Name", max_length=100)
    description = models.TextField("Description", default='')
    game_image_url = models.URLField(max_length=200, blank=True, null=True)
    price = models.DecimalField("Price", max_digits=7, decimal_places=2, default=0.0)
    old_price = models.DecimalField("Old Price", max_digits=7, decimal_places=2, null=True, blank=True)
    discount_value = models.DecimalField("Discount", max_digits=7, decimal_places=2, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("ps_monitor:item_detail", kwargs={"slug": self.name})

ps_store_monitor/ps_monitor/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

from ps_monitor.models import GameItem, UrlItem


class GameItemView(ListView):
    model = GameItem
    slug_field = "name"
    template_name = "ps_monitor/gameitem_detail.html"

    def get_queryset(self):
        queryset = GameItem.objects.filter(url_item__in=UrlItem.objects.filter(user=self.request.user))\
            .filter(name=self.kwargs['slug']).order_by('-updated_at')
        return queryset


class GameItemListView(LoginRequiredMixin, ListView):
    model = GameItem
    queryset = GameItem.objects.all()
    template_name = 'ps_monitor/home.html'

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        urls = UrlItem.objects.filter(user=self.request.user)
        items = []
        for url in urls:
            gameitem = GameItem.objects.filter(url_item=url).order_by('-updated_at').first()
            items.append(gameitem)

        context['items'] = items
        return context


class GameItemNewlyAddedListView(ListView):
    model = GameItem
    queryset = GameItem.objects.filter()
    template_name = 'ps_monitor/newly_added.html'


class GameItemCreate(CreateView):
    model = UrlItem
    fields = ['name', 'url']
    success_url = reverse_lazy('ps_monitor:newly_added')

    def form_valid(self, form):
        self.item = form.save(commit=False)
        self.item.user = self.request.user
        self.item.save()
        return redirect('ps_monitor:home')


def watch_unwatch(request, pk):

    # item = GameItem.objects.filter(pk=pk).first()
    # if not item.newly_added:
    #     item.newly_added = not item.newly_added
    #     item.save()

    return redirect('ps_monitor:home')


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('ps_monitor:home')
    else:
        form = UserCreationForm()
    return render(request, 'ps_monitor/signup.html', {'form': form})

ps_store_monitor/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Game Items</title>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-teal-300 flex flex-col min-h-screen">

{#Navigation#}
{% include 'include/header.html' %}
{#end nabigation#}

{#BODY#}
<div class="flex-grow">
    {% block content %}
    {% endblock content %}
</div>

{#End BODY#}


{% include 'include/footer.html' %}
</body>
</html>

ps_store_monitor/templates/include/footer.html
<!-- component -->
<footer class="flex justify-center px-4 text-teal-100 bg-teal-800">
    <div class="container py-6">
        <div class="flex justify-center mt-6">
            <div class="bg-white rounded-lg">
                <div class="flex flex-wrap justify-between md:flex-row">
                    <input type="email" class="m-1 p-2 appearance-none text-teal-800 text-sm focus:outline-none"
                           placeholder="Enter your email">
                    <button class="w-full m-1 p-2 text-sm bg-teal-900 rounded-lg font-semibold uppercase lg:w-auto">
                        subscribe
                    </button>
                </div>
            </div>
        </div>

        <hr class="h-px mt-6 bg-teal-800 border-none">

        <div class="flex flex-col items-center justify-between mt-6 md:flex-row">
            <div class="flex mt-4 md:m-0">
                <div class="-mx-4">
                    <a href="#" class="px-4 text-sm">About</a>
                    <a href="#" class="px-4 text-sm">Blog</a>
                    <a href="#" class="px-4 text-sm">News</a>
                    <a href="#" class="px-4 text-sm">Contact</a>
                </div>
            </div>
        </div>
    </div>
</footer>

ps_store_monitor/templates/include/header.html
<nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
        <svg class="fill-current h-8 w-8 mr-2" width="54" height="54" viewBox="0 0 54 54"
             xmlns="http://www.w3.org/2000/svg">
            <path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"/>
        </svg>
        <span class="font-semibold text-xl tracking-tight">
            <a href="{% url 'ps_monitor:home' %}">PS Game Monitor</a>
            </span>
    </div>
    <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title>
                <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
            </svg>
        </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
        <div class="text-m lg:flex-grow">
            <a href="{% url 'ps_monitor:newly_added' %}" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
                Newly Added
            </a>
            <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
                Examples
            </a>
            <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white">
                Blog
            </a>
        </div>
        <div>
            {% if user.is_authenticated %}
                <span>Hi {{ user.username }}</span>
                <a href="{% url 'logout' %}"
                   class="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0">Logout</a>
            {% else %}
                <a href="{% url 'login' %}"
                   class="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0">Login</a>
                <a href="{% url 'ps_monitor:signup' %}"
                   class="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0">Sign in</a>
            {% endif %}
        </div>
    </div>
</nav>

ps_store_monitor/templates/ps_monitor/gameitem_detail.html
{% extends 'base.html' %}
{% block content %}
    {% for gameitem in gameitem_list %}
        <br/>
        <h1>Item Details</h1>
        <h2>Name: {{ gameitem.name }}</h2>
        url: {{ gameitem.url }}
        <br/>
        updated_at: {{ gameitem.updated_at }}
        <br/>
        <br/>
    {% endfor %}
{% endblock %}

ps_store_monitor/templates/ps_monitor/gameitem_form.html
{% extends 'base.html' %}
{% block content %}
    <h1>Create Item for monitor</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

ps_store_monitor/templates/ps_monitor/home.html
{% extends 'base.html' %}
{% block content %}
    {% for gameitem in items %}
        <div class="bg-teal-300 hover:bg-teal-200 py-1">
            <div class="md:flex shadow-lg  mx-6 md:mx-auto my-4 max-w-lg md:max-w-5xl h-auto">
                {% if not gameitem.game_image_url %}
                    <svg class="h-full w-full md:w-1/4  object-cover rounded-lg rounded-r-none pb-5/6"
                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                    </svg>

                {% else %}
                    <img class="h-full w-full md:w-1/4  object-cover rounded-lg rounded-r-none pb-5/6"
                         src="{{ gameitem.game_image_url }}" alt="{{ gameitem.name }}">
                {% endif %}
                <div class="w-full md:w-3/4 px-4 py-4 bg-white rounded-r-lg border border-teal-900">
                    <div class="flex items-center">
                        <h2 class="text-xl text-gray-800 font-medium mr-auto">{{ gameitem.name }}</h2>
                        <p class="text-gray-800 font-semibold tracking-tighter">
                            {% if gameitem.old_price %}
                                only
                                <i class="text-gray-600 line-through">{{ gameitem.price }} $</i>

                                <span class="text-xl">
                                        {{ gameitem.old_price }}$
                                    </span>
                            {% else %}
                                <span class="text-xl">
                                     {{ gameitem.price }} $
                                    </span>

                            {% endif %}
                        </p>
                    </div>
                    <p class="text-sm text-gray-700 mt-4">
                        {{ gameitem.description }}
                    </p>
                    <div class="flex items-center justify-end mt-4 top-auto pt-5">
                        <button class="bg-white text-red-500 px-4 py-2 rounded mr-auto hover:underline">Delete</button>

                        <form action="{% url 'ps_monitor:watch_unwatch' pk=gameitem.id %}" method=POST>
                            {% csrf_token %}
                            <button class="flex items-center bg-blue-600 text-gray-200 px-2 py-2 rounded-md  mr-2">
                                <svg class="w-5 inline-block mr-2" xmlns="http://www.w3.org/2000/svg" fill="none"
                                     viewBox="0 0 24 24"
                                     stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"></path>
                                </svg>
                                UnTrack
                            </button>
                        </form>
                        <a href="{{ gameitem.get_absolute_url }}">
                            <button class=" bg-gray-200 text-blue-600 px-2 py-2 rounded-md">Details</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock content %}

ps_store_monitor/templates/ps_monitor/newly_added.html
{% extends 'base.html' %}
{% block content %}

    <div class="flex justify-center">
        <div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md">
            <div class="flex justify-between items-center">
                <span class="font-light text-gray-600">mar 10, 2019</span>
                <a class="px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500" href="#">
                    <svg class="w-5 inline-block pb-1 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none"
                         viewBox="0 0 24 24"
                         stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"></path>
                    </svg>
                    Track
                </a>
            </div>
            <div class="mt-2">
                <a class="text-2xl text-gray-700 font-bold hover:text-gray-600" href="#">Accessibility tools for
                    designers
                    and developers</a>
                <p class="mt-2 text-gray-600">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita
                    dicta totam aspernatur doloremque. Excepturi iste iusto eos enim reprehenderit nisi, accusamus
                    delectus
                    nihil quis facere in modi ratione libero!</p>
            </div>
        </div>
    </div>

{% endblock %}

ps_store_monitor/templates/ps_monitor/signup.html
{% extends 'base.html' %}

{% block content %}
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}

ps_store_monitor/templates/ps_monitor/urlitem_form.html
{% extends 'base.html' %}
{% block content %}
    <h1>Create Item for monitor</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}